import { Medicine, Job, BlogPost, Testimonial } from './types';
import { Pill, Activity, Heart, Thermometer, ShieldCheck } from 'lucide-react';

export const MEDICINES: Medicine[] = [
  {
    id: 'm1',
    name: 'Paracetamol',
    brand: 'Crocin',
    dosage: '650 mg',
    isPrescriptionRequired: false,
    price: 35,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Noble Chemists, Andheri West',
    distance: '0.3 km',
    deliveryTime: '8–12 mins',
    category: 'Pain Relief',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=300&fit=crop'
  },
  {
    id: 'm2',
    name: 'Azithromycin',
    brand: 'Azee',
    dosage: '500 mg',
    isPrescriptionRequired: true,
    price: 120,
    currency: '₹',
    availability: 'Limited Stock',
    pharmacyName: 'Wellness Forever, Bhavan\'s College',
    distance: '0.5 km',
    deliveryTime: '15–20 mins',
    category: 'Antibiotics',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=300&fit=crop'
  },
  {
    id: 'm3',
    name: 'Metformin',
    brand: 'Glycomet',
    dosage: '500 mg',
    isPrescriptionRequired: true,
    price: 90,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Apollo Pharmacy, Azad Nagar',
    distance: '1.2 km',
    deliveryTime: '12–18 mins',
    category: 'Diabetes',
    image: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&h=300&fit=crop'
  },
  {
    id: 'm4',
    name: 'Telmisartan',
    brand: 'Telma',
    dosage: '40 mg',
    isPrescriptionRequired: true,
    price: 110,
    currency: '₹',
    availability: 'Out of Stock',
    pharmacyName: 'Royal Chemists, DN Nagar',
    distance: '1.5 km',
    deliveryTime: '25–30 mins',
    category: 'Blood Pressure',
    image: 'https://images.unsplash.com/photo-1587854692152-cbe660dbde88?w=400&h=300&fit=crop'
  },
  {
    id: 'm5',
    name: 'Cetirizine',
    brand: 'Cetzine',
    dosage: '10 mg',
    isPrescriptionRequired: false,
    price: 25,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'HealthPlus, Versova',
    distance: '2.0 km',
    deliveryTime: '20–25 mins',
    category: 'Cold & Allergy',
    image: 'https://images.unsplash.com/photo-1585435557343-3b092031a831?w=400&h=300&fit=crop'
  },
  {
    id: 'm6',
    name: 'Dolo',
    brand: 'Micro Labs',
    dosage: '650 mg',
    isPrescriptionRequired: false,
    price: 30,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Noble Chemists, Andheri West',
    distance: '0.3 km',
    deliveryTime: '5–10 mins',
    category: 'Pain Relief',
    image: 'https://images.unsplash.com/photo-1631549916768-4119b2e5f926?w=400&h=300&fit=crop'
  },
  {
    id: 'm7',
    name: 'Amoxycillin + Clavulanic Acid',
    brand: 'Augmentin',
    dosage: '625 mg',
    isPrescriptionRequired: true,
    price: 200,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Wellness Forever, Bhavan\'s College',
    distance: '0.5 km',
    deliveryTime: '15–20 mins',
    category: 'Antibiotics',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=300&fit=crop'
  },
  {
    id: 'm8',
    name: 'Sitagliptin + Metformin',
    brand: 'Janumet',
    dosage: '50/500 mg',
    isPrescriptionRequired: true,
    price: 280,
    currency: '₹',
    availability: 'Limited Stock',
    pharmacyName: 'Apollo Pharmacy, Azad Nagar',
    distance: '1.2 km',
    deliveryTime: '18–22 mins',
    category: 'Diabetes',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=300&fit=crop'
  },
  {
    id: 'm9',
    name: 'Amlodipine',
    brand: 'Amlong',
    dosage: '5 mg',
    isPrescriptionRequired: true,
    price: 45,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Metro Chemist, JP Road',
    distance: '0.8 km',
    deliveryTime: '10–15 mins',
    category: 'Blood Pressure',
    image: 'https://images.unsplash.com/photo-1628771065518-0d82f1938462?w=400&h=300&fit=crop'
  },
  {
    id: 'm10',
    name: 'Fexofenadine',
    brand: 'Allegra',
    dosage: '120 mg',
    isPrescriptionRequired: false,
    price: 180,
    currency: '₹',
    availability: 'Out of Stock',
    pharmacyName: 'HealthPlus, Versova',
    distance: '2.1 km',
    deliveryTime: '25–30 mins',
    category: 'Cold & Allergy',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=300&fit=crop'
  },
  {
    id: 'm11',
    name: 'Ibuprofen + Paracetamol',
    brand: 'Combiflam',
    dosage: '400/325 mg',
    isPrescriptionRequired: false,
    price: 40,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Suburban Diagnostics & Pharmacy',
    distance: '1.0 km',
    deliveryTime: '15–20 mins',
    category: 'Pain Relief',
    image: 'https://images.unsplash.com/photo-1550572017-4fcdbb59cc32?w=400&h=300&fit=crop'
  },
  {
    id: 'm12',
    name: 'Vildagliptin',
    brand: 'Galvus',
    dosage: '50 mg',
    isPrescriptionRequired: true,
    price: 220,
    currency: '₹',
    availability: 'Limited Stock',
    pharmacyName: 'Noble Chemists, Andheri West',
    distance: '0.3 km',
    deliveryTime: '8–12 mins',
    category: 'Diabetes',
    image: 'https://images.unsplash.com/photo-1512069772995-ec65ed45afd6?w=400&h=300&fit=crop'
  },
  // New medicines added
  {
    id: 'm13',
    name: 'Aspirin',
    brand: 'Ecosprin',
    dosage: '75 mg',
    isPrescriptionRequired: false,
    price: 15,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Apollo Pharmacy, Azad Nagar',
    distance: '1.2 km',
    deliveryTime: '12–18 mins',
    category: 'Pain Relief',
    image: 'https://images.unsplash.com/photo-1626716493137-b67fe9501e76?w=400&h=300&fit=crop'
  },
  {
    id: 'm14',
    name: 'Diclofenac',
    brand: 'Voveran',
    dosage: '50 mg',
    isPrescriptionRequired: true,
    price: 55,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Metro Chemist, JP Road',
    distance: '0.8 km',
    deliveryTime: '10–15 mins',
    category: 'Pain Relief',
    image: 'https://images.unsplash.com/photo-1573883431205-98b5f10f8e55?w=400&h=300&fit=crop'
  },
  {
    id: 'm15',
    name: 'Omeprazole',
    brand: 'Omez',
    dosage: '20 mg',
    isPrescriptionRequired: false,
    price: 65,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Wellness Forever, Bhavan\'s College',
    distance: '0.5 km',
    deliveryTime: '15–20 mins',
    category: 'Digestive Health',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&h=300&fit=crop'
  },
  {
    id: 'm16',
    name: 'Pantoprazole',
    brand: 'Pan-D',
    dosage: '40 mg',
    isPrescriptionRequired: false,
    price: 85,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Noble Chemists, Andheri West',
    distance: '0.3 km',
    deliveryTime: '8–12 mins',
    category: 'Digestive Health',
    image: 'https://images.unsplash.com/photo-1603807008857-ad66b70431e2?w=400&h=300&fit=crop'
  },
  {
    id: 'm17',
    name: 'Montelukast',
    brand: 'Montair',
    dosage: '10 mg',
    isPrescriptionRequired: true,
    price: 140,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'HealthPlus, Versova',
    distance: '2.0 km',
    deliveryTime: '20–25 mins',
    category: 'Cold & Allergy',
    image: 'https://images.unsplash.com/photo-1583947215259-38e31be8751f?w=400&h=300&fit=crop'
  },
  {
    id: 'm18',
    name: 'Levocetirizine',
    brand: 'Xyzal',
    dosage: '5 mg',
    isPrescriptionRequired: false,
    price: 45,
    currency: '₹',
    availability: 'Limited Stock',
    pharmacyName: 'Apollo Pharmacy, Azad Nagar',
    distance: '1.2 km',
    deliveryTime: '12–18 mins',
    category: 'Cold & Allergy',
    image: 'https://images.unsplash.com/photo-1579165466949-3180a3d056d5?w=400&h=300&fit=crop'
  },
  {
    id: 'm19',
    name: 'Losartan',
    brand: 'Losar',
    dosage: '50 mg',
    isPrescriptionRequired: true,
    price: 95,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Royal Chemists, DN Nagar',
    distance: '1.5 km',
    deliveryTime: '25–30 mins',
    category: 'Blood Pressure',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop'
  },
  {
    id: 'm20',
    name: 'Atenolol',
    brand: 'Aten',
    dosage: '50 mg',
    isPrescriptionRequired: true,
    price: 35,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Suburban Diagnostics & Pharmacy',
    distance: '1.0 km',
    deliveryTime: '15–20 mins',
    category: 'Blood Pressure',
    image: 'https://images.unsplash.com/photo-1544991875-5dc1b05f607d?w=400&h=300&fit=crop'
  },
  {
    id: 'm21',
    name: 'Ciprofloxacin',
    brand: 'Ciplox',
    dosage: '500 mg',
    isPrescriptionRequired: true,
    price: 75,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Metro Chemist, JP Road',
    distance: '0.8 km',
    deliveryTime: '10–15 mins',
    category: 'Antibiotics',
    image: 'https://images.unsplash.com/photo-1471864190281-a93a3070b6de?w=400&h=300&fit=crop'
  },
  {
    id: 'm22',
    name: 'Doxycycline',
    brand: 'Doxy',
    dosage: '100 mg',
    isPrescriptionRequired: true,
    price: 110,
    currency: '₹',
    availability: 'Limited Stock',
    pharmacyName: 'Wellness Forever, Bhavan\'s College',
    distance: '0.5 km',
    deliveryTime: '15–20 mins',
    category: 'Antibiotics',
    image: 'https://images.unsplash.com/photo-1559757175-5700dde675bc?w=400&h=300&fit=crop'
  },
  {
    id: 'm23',
    name: 'Glimepiride',
    brand: 'Amaryl',
    dosage: '2 mg',
    isPrescriptionRequired: true,
    price: 150,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Apollo Pharmacy, Azad Nagar',
    distance: '1.2 km',
    deliveryTime: '12–18 mins',
    category: 'Diabetes',
    image: 'https://images.unsplash.com/photo-1550572017-edd951b55104?w=400&h=300&fit=crop'
  },
  {
    id: 'm24',
    name: 'Pioglitazone',
    brand: 'Pioz',
    dosage: '15 mg',
    isPrescriptionRequired: true,
    price: 180,
    currency: '₹',
    availability: 'Out of Stock',
    pharmacyName: 'Noble Chemists, Andheri West',
    distance: '0.3 km',
    deliveryTime: '8–12 mins',
    category: 'Diabetes',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=400&h=300&fit=crop'
  },
  {
    id: 'm25',
    name: 'Ranitidine',
    brand: 'Rantac',
    dosage: '150 mg',
    isPrescriptionRequired: false,
    price: 40,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'HealthPlus, Versova',
    distance: '2.0 km',
    deliveryTime: '20–25 mins',
    category: 'Digestive Health',
    image: 'https://images.unsplash.com/photo-1584017911766-d451b3d0e843?w=400&h=300&fit=crop'
  },
  {
    id: 'm26',
    name: 'Domperidone',
    brand: 'Domstal',
    dosage: '10 mg',
    isPrescriptionRequired: false,
    price: 35,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Metro Chemist, JP Road',
    distance: '0.8 km',
    deliveryTime: '10–15 mins',
    category: 'Digestive Health',
    image: 'https://images.unsplash.com/photo-1603807008857-ad66b70431e2?w=400&h=300&fit=crop'
  },
  {
    id: 'm27',
    name: 'Vitamin D3',
    brand: 'Calcirol',
    dosage: '60000 IU',
    isPrescriptionRequired: false,
    price: 120,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Noble Chemists, Andheri West',
    distance: '0.3 km',
    deliveryTime: '8–12 mins',
    category: 'Vitamins',
    image: 'https://images.unsplash.com/photo-1616671276441-2f2c277b8bf6?w=400&h=300&fit=crop'
  },
  {
    id: 'm28',
    name: 'Multivitamin',
    brand: 'Supradyn',
    dosage: '1 Tablet',
    isPrescriptionRequired: false,
    price: 95,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'Apollo Pharmacy, Azad Nagar',
    distance: '1.2 km',
    deliveryTime: '12–18 mins',
    category: 'Vitamins',
    image: 'https://images.unsplash.com/photo-1584308666744-24d5c474f2ae?w=400&h=300&fit=crop'
  },
  {
    id: 'm29',
    name: 'Calcium + Vitamin D',
    brand: 'Shelcal',
    dosage: '500 mg',
    isPrescriptionRequired: false,
    price: 180,
    currency: '₹',
    availability: 'Limited Stock',
    pharmacyName: 'Wellness Forever, Bhavan\'s College',
    distance: '0.5 km',
    deliveryTime: '15–20 mins',
    category: 'Vitamins',
    image: 'https://images.unsplash.com/photo-1559757148-5c350d0d3c56?w=400&h=300&fit=crop'
  },
  {
    id: 'm30',
    name: 'Iron + Folic Acid',
    brand: 'Autrin',
    dosage: '100 mg',
    isPrescriptionRequired: false,
    price: 75,
    currency: '₹',
    availability: 'In Stock',
    pharmacyName: 'HealthPlus, Versova',
    distance: '2.0 km',
    deliveryTime: '20–25 mins',
    category: 'Vitamins',
    image: 'https://images.unsplash.com/photo-1607619056574-7b8d3ee536b2?w=400&h=300&fit=crop'
  }
];

export const JOBS: Job[] = [
  {
    id: 'j1',
    title: 'Pharmacy Network Manager',
    department: 'Operations',
    location: 'Mumbai, India',
    type: 'Full-time'
  },
  {
    id: 'j2',
    title: 'Senior React Engineer',
    department: 'Engineering',
    location: 'Remote / Mumbai',
    type: 'Full-time'
  },
  {
    id: 'j3',
    title: 'Customer Success Executive',
    department: 'Support',
    location: 'Mumbai, India',
    type: 'Full-time'
  },
  {
    id: 'j4',
    title: 'Delivery Partner (Hyperlocal)',
    department: 'Logistics',
    location: 'Andheri West, Mumbai',
    type: 'Contract'
  }
];

export const BLOG_POSTS: BlogPost[] = [
  {
    id: 'b1',
    title: 'Managing Diabetes in Indian Summers',
    excerpt: 'Tips for senior citizens to stay hydrated and manage blood sugar levels during the heatwave.',
    date: 'Oct 12, 2023',
    author: 'Dr. R. Mehta',
    readTime: '5 min read',
    image: 'https://images.unsplash.com/photo-1579684385127-1ef15d508118?w=600&h=400&fit=crop'
  },
  {
    id: 'b2',
    title: 'Understanding Generic vs. Branded Medicines',
    excerpt: 'Why generic medicines are just as effective and how they can save you money on monthly prescriptions.',
    date: 'Sep 28, 2023',
    author: 'S. Gupta, PharmD',
    readTime: '7 min read',
    image: 'https://images.unsplash.com/photo-1576602976047-174e57a47881?w=600&h=400&fit=crop'
  },
  {
    id: 'b3',
    title: 'The Rise of Hyperlocal Pharmacy Delivery',
    excerpt: 'How MediFind is connecting local pharmacists with neighbors to ensure 30-minute delivery.',
    date: 'Sep 15, 2023',
    author: 'MediFind Team',
    readTime: '4 min read',
    image: 'https://images.unsplash.com/photo-1563013544-824ae1b704d3?w=600&h=400&fit=crop'
  }
];

export const TESTIMONIALS: Testimonial[] = [
  {
    id: 't1',
    name: 'Rajesh Kumar',
    role: 'Caregiver for elderly parents',
    content: "MediFind has been a lifesaver. I can reserve my father's BP medicines at the shop next door and pick them up on my way home. No more waiting in lines.",
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=100&h=100&fit=crop&crop=face'
  },
  {
    id: 't2',
    name: 'Mrs. Lakshmi Iyer',
    role: 'Retired Teacher',
    content: "The app is so easy to use. I can see if the medicine is actually in stock before walking to the pharmacy. Very helpful for seniors like me.",
    avatar: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?w=100&h=100&fit=crop&crop=face'
  },
  {
    id: 't3',
    name: 'Amit Singh',
    role: 'Pharmacy Owner',
    content: "Since joining MediFind, our local visibility has increased. We are serving customers we didn't know existed in our own neighborhood.",
    avatar: 'https://images.unsplash.com/photo-1472099645785-5658abf4ff4e?w=100&h=100&fit=crop&crop=face'
  }
];

export const CATEGORIES = [
  { name: 'Pain Relief', icon: Activity },
  { name: 'Diabetes', icon: Thermometer },
  { name: 'Antibiotics', icon: Pill },
  { name: 'Blood Pressure', icon: Heart },
  { name: 'Cold & Allergy', icon: ShieldCheck },
  { name: 'Digestive Health', icon: Activity },
  { name: 'Vitamins', icon: Heart },
];